---
title: "Coho FRAM Applications"
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE, results = 'hide', warning = FALSE, message = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.height=9, fig.width=9)
```

# 1. Pre-season model input development

The process for developing the <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Fishery_Regulation_Assessment_Model_(FRAM)" target = "_blank" title = "FRAM: Fishery Regulation Assessment Model">FRAM</a> model inputs used to assess upcoming fishing season negotiations begins with the forecasting of <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Hatchery" target = "_blank" title = "Hatchery">hatchery</a> and wild/<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Natural" target = "_blank" title = "Natural">natural</a> stock abundances.  Fishery inputs for <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> are generally developed through the pre-season process.  Fishery-related mortality parameters, such as release mortality rates, drop-off, and <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Mark-selective_Fishery_(MSF)" target = "_blank" title = "MSF: Mark-selective fishery">mark-selective fishery</a> parameters, are reviewed and confirmed at the start of the annual management cycle.  Many of these rates do not change from year to year, while some are the result of manager agreements made in previous years based on research study results, and some are updated annually based on monitoring data (**see Section 3**).  In the cases where research study results may be lacking, such as <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Marked_Recognition_Error_Rate" target = "_blank" title = "Marked recognition error rate">marked recognition error</a> in new mark-selective fisheries, *ad hoc* values are established following technical staff discussions and manager agreement.   

## 1.1. Stock Abundance

A variety of methods are used to forecast abundances of coho. These forecasts are usually developed by local/regional technical staff during one or more technical meetings where relevant forecasting information is exchanged.  Final agreed-to forecasts are regularly published in the <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Pacific_Fishery_Management_Council_(PFMC)" target = "_blank" title = "PFMC: Pacific Fishery Management Council">PFMC</a> Salmon Technical Team pre-season reports (Stock Assessment and Fishery Evaluation; SAFE).

<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Abundance_Forecast" target = "_blank" title = "Abundance forecasts">Abundance forecasts</a> vary in units of measure.  For example, there are forecasts of salmon returning to a terminal area (which implies some accounting for pre-terminal fishery levels), forecasts of ocean abundance (which is commonly fishery impacts plus <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Escapement" target = "_blank" title = "Escapement">escapement</a>), and forecasts of abundances prior to any fishing impacts (which includes <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Natural_Mortality" target = "_blank" title = "Natural mortality">natural mortality</a> and <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Non-landedNon-retention_Mortality" target = "_blank" title = "Non-landed mortality">non-landed</a> fishery related mortality). Each of these different types of forecasts need to be converted to the “unit of measure” used by <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span>, which is the abundance of each stock prior to fishing vulnerability and natural mortality.  This starting coho <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> unit of measure is characterized as January-age-3 fish. <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> stock abundances are input as a scaler where the forecasted number of fish prior to fishing and natural mortality is divided by the <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Base_Period" target = "_blank" title = "Base period">base period</a> average abundance for each stock.  
 
Coho forecasts supplied by the local/regional technical staff vary in methods and units of measure.  Forecasts can be in terms of age 3 ocean abundance (<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Ocean_Age-3_Abundance_(OA3)" target = "_blank" title = "OA3: Ocean age 3">OA3</a>) (i.e., all catch and escapement), return to a terminal area, or in starting <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> January-age-3 fish (<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#January_Age-3_Abundance_(JA3)" target = "_blank" title = "JA3: January age-3 abundance">JA3</a>).  Many U.S. domestic and Pacific Salmon Treaty (PST) international coho management objectives are specified in age 3 ocean abundance units.  Thus, most of the forecasts are produced in terms of age 3 ocean abundance, which are then expanded by 1.2317 to account for natural mortality and provide an estimate of age-3 fish abundance in January of the fishing year (<span title = "OA3: Ocean age 3 abundance">OA3</span> * 1.2317 = <span title = "JA3: January age 3 abundance">JA3</span>).  The value 1.2317 is a result of a two-step conversion due to a prior December age 2 (DA2) unit of measure used in modeling before <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> (1.2317 = 1.333 (convert <span title = "OA3: Ocean age 3 abundance">OA3</span> to <span title = "DA2: December age 2 abundance">DA2</span>) * 0.924 (convert <span title = "DA2: December age 2 abundance">DA2</span> to <span title = "JA3: January age 3 abundance">JA3</span>)).  Any non-landed fishery related mortality that occurs is ignored in this ocean abundance-to-total abundance <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> conversion step.  

## 1.2. Fisheries

Fisheries are modeled using <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> input methods which are fairly consistent in yearly pre-season model runs.  The data and methods used to generate fishery inputs for <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> and <span title = "TAMM: Terminal Area Management Module">TAMM</span> are shared, discussed, and agreed-to by salmon <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Co-managers" target = "_blank" title = "Co-managers">co-manager</a> technical staff in the <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#North_of_Falcon_(NOF)" target = "_blank" title = "NOF: North of Falcon">NOF</a> annual process.  Generally, <span title = "PFMC: Pacific Fishery Management Council">PFMC</span>-managed ocean fisheries north of <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Cape_Falcon" target = "_blank" title = "Cape Falcon">Cape Falcon</a> are modeled as <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Landed_Catch" target = "_blank" title = "Landed catch">landed catch</a> quotas.  Fisheries outside of <span title = "PFMC: Pacific Fishery Management Council">PFMC</span> jurisdiction are modeled using a variety of the <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> methods available.  

<span title = "PFMC: Pacific Fishery Management Council">PFMC</span>-managed coho retention fisheries are modeled as landed fish quotas or mark-selective fishery quotas (i.e., retained <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Marked" target = "_blank" title = "marked">marked</a> fish).  <span title = "PFMC: Pacific Fishery Management Council">PFMC</span>-managed coho non-retention fisheries are modeled using external estimates of mortalities generated from historical coho to Chinook ratios of landings when retention of both species was allowed.  In some fisheries, like the troll fisheries South of Cape Falcon, these external mortality estimates are adjusted downward to account for shifts in effort away from the species that cannot be retained.  Fisheries outside of <span title = "PFMC: Pacific Fishery Management Council">PFMC</span> jurisdiction are modeled using quotas as a landed catch expectation, as catch (or occasionally effort) scalers, or as terminal area <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Harvest_Rate_(HR)" target = "_blank" title = "HR: Harvest rate">harvest rates</a> used during <span title = "TAMM: Terminal Area Management Module">TAMM</span> processing.  Canadian fisheries are modeled using <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Fishery_Scaler" target = "_blank" title = "Fishery scaler">fishery scalers</a> generated from post-season <span title = "PST: Pacific Salmon Treaty">PST</span> Coho <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> modeling exercises, which represent similar fishery expectations or regulations in the upcoming fishing year.  Alaskan fisheries are modeled pre-season using static scalers to represent current stock abundances relative to coho <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> base period fishing. 

# 2. Post-season Model Usage

Although <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> is primarily used for pre-season fishery impact assessment, it can also be used in a post-season context.  These post-season model runs can be used as a tool to evaluate the model's performance by comparing model estimates to independently derived estimates, and to evaluate the performance of the fishery management system towards meeting conservation objectives for key stocks.

Post-season <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> runs use the “backwards” <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> (<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Backwards_FRAM_(BkFRAM)" target = "_blank" title = "Backwards FRAM">bkFRAM</a>) utility that finds <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> starting abundances by providing estimates of escapements and fishery catches (landed and non-retention).  This context uses the <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> model to estimate what occurred in a previous year based on observed input values and the associated estimated abundances. Post-season model runs are conducted by the Pacific Salmon Commission (<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Pacific_Salmon_Commission_(PSC)" target = "_blank" title = "PSC: Pacific Salmon Commission">PSC</a>) Coho Technical Committee(CoTC) every year during the <span title = "PSC: Pacific Salmon Commission">PSC</span> annual meeting and used to evaluate management obligations under the <span title = "PST: Pacific Salmon Treaty">PST</span>.  Post-season model runs are often lagged by several years due to data availability issues.    
