---
title: "Chinook FRAM Applications"
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE, results = 'hide', warning = FALSE, message = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.height=9, fig.width=9)
```

# 1. Pre-season Model Input Development

The process for developing the <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Fishery_Regulation_Assessment_Model_(FRAM)" target = "_blank" title = "FRAM: Fishery Regulation Assessment Model">FRAM</a> model inputs used to assess upcoming fishing season negotiations begins with the forecasting of <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Hatchery" target = "_blank" title = "Hatchery">hatchery</a> and wild/<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Natural" target = "_blank" title = "Natural">natural</a> <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Stock" target = "_blank" title = "Stock">stock</a> abundances.  Fishery inputs for <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> are generally developed through the <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Pre-season" target = "_blank" title = "Pre-season">pre-season</a> process.  Fishery-related mortality <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Parameter" target = "_blank" title = "Parameter">parameters</a>, such as release mortality rates, drop-off, and <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Mark-selective_Fishery_(MSF)" target = "_blank" title = "MSF: Mark-selective fishery">mark-selective fishery</a> parameters, are reviewed and confirmed at the start of the annual management cycle.  Many of these rates do not change from year to year, while some are the result of manager agreements made in previous years based on research study results, and some are updated annually based on monitoring data (<a target = "FRAM input data" href = "https://framverse.github.io/fram_doc/calcs_data_chin.html#2_Model_Parameterization" target = "_blank">Model input data</a>).  In the cases where research study results may be lacking, such as <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Marked_Recognition_Error_Rate" target = "_blank" title = "Marked recognition error rate">marked recognition error</a> in new mark-selective fisheries, *ad hoc* values are established following technical staff discussions and manager agreement. 

## 1.1. Stock Abundance

A variety of methods are used to forecast abundances of coho and Chinook.  These forecasts are usually developed by local/regional technical staff during one or more technical meetings where relevant forecasting information is exchanged.  Final agreed-to forecasts are regularly published in the <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Pacific_Fishery_Management_Council_(PFMC)" target = "_blank" title = "PFMC: Pacific Fishery Management Council">PFMC</a> Salmon Technical Team pre-season reports (Stock Assessment and Fishery Evaluation; SAFE).

<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Abundance_Forecast" target = "_blank" title = "Abundance forecasts">Abundance forecasts</a> vary in units of measure.  For example, there are forecasts of salmon returning to a terminal area (which implies some accounting for <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Pre-terminal_Fishery" target = "_blank" title = "Pre-terminal fishery">pre-terminal fishery</a> levels), forecasts of ocean abundance (which is commonly fishery impacts plus <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Escapement" target = "_blank" title = "Escapement">escapement</a>), and forecasts of abundances prior to any fishing impacts (which includes <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Natural_Mortality" target = "_blank" title = "Natural mortality">natural mortality</a> and <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Non-landedNon-retention_Mortality" target = "_blank" title = "Non-landed mortality">non-landed</a> fishery related mortality).  The forecasts that are based on expectations of fish returning to the terminal area need to account for pre-terminal fishing impacts or impacts that occurred in previous seasons in the case of Chinook.  Each of these different types of forecasts need to be converted to the “unit of measure” used by <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span>, which is the abundance at age of each stock prior to fishing vulnerability and natural mortality. <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Starting_Cohort" target = "_blank" title = "Starting cohort">starting cohorts</a> are produced by <span title = "Backwards FRAM">BkFRAM</span>.

Although abundance forecasts vary in units of measure, the desired units for Chinook are either Terminal Run Size (<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Terminal_Run_Size" target = "_blank" title = "TRS: Terminal run size">TRS</a>) or 
The process for developing the <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> starting cohorts, by stock, age and <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Marked" target = "_blank" title = "marked">mark</a> status. TRS forecasts are defined as a forecast of the total fish ages 3-5 of a stock including escapement, freshwater mortalities, extreme terminal, and terminal net fishery mortalities.  TRS forecasts are then run through a "Backward" 
The process for developing the <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> run (<a title = "Backwards FRAM" href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Backwards_FRAM_(BkFRAM)" target = "_blank">BkFRAM</a>), which converts it to the “unit of measure” used to initiate <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span>, the abundance at age of each stock prior to fishing and natural mortality.  Abundance of age 2 fish are either forecasted separately and provided as a model input or can be generated using an “age 2 from 3” feature in <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> (see <a href = "https://framverse.github.io/fram_doc/user_prereq.html" target = "_blank">FRAM User Manual</a>).

## 1.2. Fisheries

Chinook <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> is the primary tool used to plan and assess pre-season fishery packages for <span title = "PFMC: Pacific Fishery Management Council">PFMC</span> fisheries north of Cape Falcon in addition to Puget Sound and Strait of Juan de Fuca fisheries through the “North of Falcon” (<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#North_of_Falcon_(NOF)" target = "_blank" title = "NOF: North of Falcon">NOF</a>) process.  While a variety of methods are used to model fisheries in a pre-season context, the methods used for each fishery are generally consistent between years.

<span title = "PFMC: Pacific Fishery Management Council">PFMC</span>-managed Chinook fisheries are modeled by the STT and the input type varies based on the management regime.  For fisheries north of Cape Falcon, which are managed based on a total allowable catch limit, quota inputs are used for both commercial troll and recreational fisheries.  Fisheries south of Cape Falcon are modeled using fishery scalers, as these fisheries are generally managed as a season.  The fishery scalers are calculated as the expected number of vessel fishing days for troll fisheries or angler trips for recreational fisheries divided by the base period average effort levels.  Effort expectations for each pre-season fishery package are provided from output of the Klamath Ocean Harvest Model.

For fisheries that are outside of  methods used to generate fishery inputs for FRAM and TAMM are shared, discussed, and agreed-to by salmon co-manager technical staff in the NOF annual process. Generally, PFMC-managed ocean fisheries north of Cape Falcon are modeled as landed catch catch in a fishery: a quotas and fisheries south of Cape Falcon are modeled as fishery scalers for Chinook. Fisheries outside of PFMC jurisdiction are modeled using a variety of the FRAM methods available. jurisdiction, including those in Puget Sound and in freshwater fisheries, <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> fishery input methods for retention fisheries include quotas (as a fixed catch), fishery effort scalers (e.g., Puget Sound marine sport) or terminal fishery harvest rates used during TAMM processing (e.g., Puget Sound terminal net).  Chinook non-retention fishery mortalities are primarily modeled using estimates of sublegal and legal-size encounters.

Fisheries north of the border between Washington and Canada are modeled based on the framework under which they are managed.  Fisheries that are subject to Aggregate Abundance Based Management (<span title = "AABM:Aggregate Abundance Based Management">AABM</span>) per the provisions of the Pacific Salmon Treaty (<span title = "Pacific Salmon Treaty">PST</span>) Agreement are managed based on catch limits set annually by the Pacific Salmon Commission (<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Pacific_Salmon_Commission_(PSC)" target = "_blank" title = "PSC: Pacific Salmon Commission">PSC</a>).  For Southeast Alaska, the total all gear (troll, net, sport) annual catch limit is determined based on the catch per unit effort observed during the winter troll fishery.  Catch limits for the Canadian <span title = "AABM:Aggregate Abundance Based Management">AABM</span> fisheries (Northern B.C. and <span title = "WCVI:West Coast Vancouver Island">WCVI</span> troll and sport) are derived annually from preseason “abundance indices” produced by the annual calibration of the <span title = "PSC: Pacific Salmon Commission">PSC</span> Chinook Model.  Catch limits for all <span title = "AABM:Aggregate Abundance Based Management">AABM</span> fisheries are allocated to gear and time period based on recent year averages and modeled as quotas.  Catch limits for the Canadian <span title = "AABM:Aggregate Abundance Based Management">AABM</span> fisheries are not available until the <span title = "PSC: Pacific Salmon Commission">PSC</span> Chinook Model calibration is completed, usually by April 1.  For model runs conducted prior to this, Canadian <span title = "AABM:Aggregate Abundance Based Management">AABM</span> fisheries are modeled using fishery scalers from the previous year’s preseason model run, which can result in increased uncertainty during the early stages of the annual assessment process.  For the remaining Canadian fisheries that are managed the Individual Stock Based Management (<span title = "ISBM:Individual Stock Based Management">ISBM</span>) provisions of the <span title = "Pacific Salmon Treaty">PST</span> Agreement, 

-------------------------------------------------------------------

Fisheries are modeled using <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> input methods which are fairly consistent in yearly pre-season model runs.  The data and methods used to generate fishery inputs for <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> and <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Terminal_Area_Management_Module_(TAMM)" target = "_blank" title = "TAMM: Terminal Area Management Module">TAMM</a> are shared, discussed, and agreed-to by salmon <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Co-managers" target = "_href" title = "Co-managers">co-manager</a> technical staff in the <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#North_of_Falcon_(NOF)" target = "_blank" title = "NOF: North of Falcon">NOF</a> annual process.  Generally, <span title = "PFMC: Pacific Fishery Management Council">PFMC</span>-managed ocean fisheries north of <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Cape_Falcon" target = "_blank" title = "Cape Falcon">Cape Falcon</a> are modeled as <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Landed_Catch" target = "_blank" title = "Landed catch">landed catch</a> <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Landed_Catch" target = "_blank" title = "Landed catch">catch</a> in a fishery: a <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Quota" target = "_blank" title = "Quota">quotas</a> and fisheries south of Cape Falcon are modeled as <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Fishery_Scaler" target = "_blank" title = "Fishery scalers">fishery scalers</a> for Chinook.  Fisheries outside of <span title = "PFMC: Pacific Fishery Management Council">PFMC</span> jurisdiction are modeled using a variety of the <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> methods available.  

Generally, fishery scalers are used for those fisheries that have relatively low Chinook model-stock representation in <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span>, such as in Alaska, Northern Canada, Central Oregon, and California.  For fisheries with a high proportion of catch from <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> stocks, any of the <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> input methods can be used.  Input type can depend on the management regime, such as for <span title = "PFMC: Pacific Fishery Management Council">PFMC</span> fisheries North of Cape Falcon which are managed for a Total Allowable Catch (i.e., quota).  Chinook <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> relies on fishery estimates derived from the Pacific Salmon Commission (<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Pacific_Salmon_Commission_(PSC)" target = "_blank" title = "PSC: Pacific Salmon Commission">PSC</a>) Chinook model as inputs for Alaskan and most Canadian fisheries.  The <span title = "PSC: Pacific Salmon Commission">PSC</span> Chinook model has better stock representation in these northern fisheries and consequently is assumed to provide a better representation of fishing effort changes relative to the <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Base_Period" target = "_blank" title = "Base period">base period</a>, which is common to both models.  Usually, fishery inputs resulting from the <span title = "PSC: Pacific Salmon Commission">PSC</span> model for the current year are not available until late in the <span title = "PFMC: Pacific Fishery Management Council">PFMC</span> management cycle.  Until these inputs are available, preliminary values or values from the previous year(s) must be used which creates greater uncertainty during the annual assessment process.

For <span title = "PFMC: Pacific Fishery Management Council">PFMC</span>-managed fisheries south of Cape Falcon, fishery scalers calculated from estimated and past fishing effort are used for inputs to the model.  Effort scalers are calculated from the expected number of vessel fishing days for <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Troll_Fishery" target = "_blank" title = "Troll fishery">troll fisheries</a> and the angler-trips for sport fisheries divided by base period average effort levels.  

For fisheries that are outside of <span title = "PFMC: Pacific Fishery Management Council">PFMC</span> jurisdiction, including those in Puget Sound and in freshwater fisheries, <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> fishery input methods for retention fisheries include quotas (as a fixed catch), fishery effort scalers (e.g., Puget Sound marine sport) or <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Terminal_Fishery" target = "_blank" title = "Terminal fishery">terminal fishery</a> <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Harvest_Rate_(HR)" target = "_blank" title = "HR: Harvest rate">harvest rates</a> used during <span title = "TAMM: Terminal Area Management Module">TAMM</span> processing (e.g., Puget Sound terminal net).  Chinook non-retention fishery mortalities are primarily modeled using estimates of <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Sublegal" target = "_blank" title = "Sublegal">sublegal</a> and <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Legal-sized" target = "_blank" title = "Legal size">legal-size</a> <a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Encounter" target = "_blank" title = "Encounter">encounters</a>. 

# 2. Post-season Model Usage

Although <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> is primarily used for pre-season fishery impact assessment, it can also be used in a <a href = https://framverse.github.io/fram_doc/calcs_glossary.html#Post-season" target = "_blank" title = "Post-season">post-season</a> context.  These post-season model runs can be used for two purposes: as a tool to evaluate the model's performance by comparing model estimates to independently derived estimates, and to evaluate the performance of the fishery management system towards meeting conservation objectives for key stocks.

Post-season <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> runs use the “backwards” <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> (<span title = "Backwards FRAM" >BkFRAM</span>) utility that finds <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> starting abundances by providing estimates of (<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Extreme_Terminal_Run_Size_(ETRS)" target = "_blank" title = "ETRS: Extreme terminal run size">extreme</a>-)terminal run sizes and fishery catches (landed and non-retention).  This context uses the <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> model to estimate what occurred in a previous year based on observed input values and the associated estimated abundances. Chinook <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> postseason model runs (<a href = "https://framverse.github.io/fram_doc/calcs_glossary.html#Validation_Runs" target = "_blank" title = "Validation runs">validation runs</a>) are conducted in even years, with a lag of two-years (e.g., in 2020 for all fishery years 2018 and prior) by <span title = "WDFW: Washington Department of Fish and Wildlife">WDFW</span> and <span title = "NWIFC: Northwest Indian Fisheries Commission">NWIFC</span> <span title = "FRAM: Fishery Regulation Assessment Model">FRAM</span> modelers.
