---
title: "User Intro"
editor_options: 
  chunk_output_type: console
---

# Basic concepts and applications

FRAM is a deterministic, discrete-time, age-structured model designed to aid planning of Chinook and coho salmon fisheries. It is designed to address the effects of multiple mixed-stock fisheries on individual stocks, each further stratified by age and mark status (and possibly hatchery origin). The model calculates fishery related mortality, including catches and non-landed impacts, imposed on the forecast abundance of each stock unit. Over time, algorithms have been added or adapted to capture changing management options, and the development platform of the application has evolved (currently implemented in Visual Basic.NET), but the basic structure of the program remains much the same as when it was conceived in the late 1970’s. FRAM remains an empirically fit tool, grounded in an approach that uses the past to inform the future.

In a given run, over the course of several time steps within a year, FRAM allocates a mixed stock cohort to catches, non-retention mortality and escapement (for coho) or escapement to the terminal area (for Chinook). This occurs by combining forecasted or observed stock run sizes and fishery practices with parameters calibrated from observations made during a fixed "base period" set of baseline years. The base period integrates fishery catches, stock age and mark composition information, and coded wire tag (CWT) recovery data to produce a calibrated reference pattern of stock distributions and stock-specific harvest rates by time-step and fishery. 

A fundamental element of FRAM calculations are the stock-age-fishery-timestep specific exploitation rates (defined as the total mortality divided by abundance, itself the sum of mortality and escapement). This expression of catch as a proportion of the available abundance is based primarily on coded wire tag release and recovery data from the Regional Mark Information System [(RMIS)](https://www.rmis.org//rmis_login.php?action=Login&system=cwt). The Chinook base period was recently updated with CWTs from catch years 2007 – 2013 (brood years 2005 – 2008), and has continued to see revision with ongoing data quality improvements. The Coho base period is comprised of CWTs from catch years 1986 – 1992.

Although some program subroutines are shared, Chinook and Coho are processed separately, with distinct time step divisions, stocks, and fisheries. The Chinook version evaluates impacts on most stock groups originating from the California Central Valley (Sacramento River), north-central Oregon coast, Columbia River, Washington coast, Puget Sound, and Southern British Columbia (see [Chinook stocks]). However, not all stocks along the West Coast of North America are represented in Chinook FRAM.  Some of the stocks that are not represented in Chinook FRAM include any stock in California except Sacramento Falls, Oregon stocks originating south of Elk River, Mid and Upriver Columbia River Springs, Snake River Springs, and Canadian stocks originating north of Georgia Strait. The Coho version evaluates impacts on a comprehensive set of stocks originating from Central California to Southeast Alaska and is considered to represent total West Coast production (see [Coho stocks]). 

In addition to FRAM, the modeling of fishery impacts for Puget Sound Chinook stock units requires a Terminal Area Management Module spreadsheet (TAMM). The Chinook TAMM passes stock and fishery inputs to FRAM. Subsequently, FRAM modeling returns output to the TAMM, which then performs additional calculations before generating reports. The Coho TAMM functions to pass Puget Sound fishery inputs to FRAM, to perform additional calculations for Washington coastal and Columbia River fisheries/stocks, and to generate reports from FRAM output. Thus, the use of both FRAM and TAMM is generally necessary for both Chinook and Coho modeling. See the [TAMM] chapter for additional details.

\

## General Framework

**Coho FRAM** see [Coho stocks and fisheries]

 - Stock groups = 246 with assignment of marked/unmarked components
 - Coho fisheries = 198
 - Terminal fisheries modeled with finer resolution, with individual freshwater fisheries
 - Five time periods = Jan-Jun, July, August, Sept, Oct-Dec 
 - Model stock proportion = if a stock is modeled, 100% of the stock is assumed to be included
 - Base period calibrated using return catch years 1986-1992. In general, used brood years from 3 years prior (1983-89), exceptions for AK/Canadian stocks with 4 yr old fish, and OR coastal ranching facilities with 2 yr old fish.  Data was reviewed through 1997, but not incorporated in a base period.  No mark-selective fisheries during BP.

**Chinook FRAM** see [Chinook stocks and fisheries]

 - Stock groups = 78 with assignment of fingerling/yearling components
 - Chinook fisheries = 73 
 - Terminal fisheries as aggregations of gears and management areas
 - Four time periods = Oct-Apr1, May-Jun, Jul-Sept, Oct-Apr2
 - Model stock proportion = stocks can be represented as <100% (i.e. only 80% included)
 - Base period calibrated using 2005-08 brood year CWT releases (return catch years 2007-13).  First used in 2017 preseason planning, with a revised “new” version for 2018 preseason and another updated version for 2019 preseason.  These years include mark-selective fisheries.

\

